---
- name: Create manifests directory on first master
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Copy vip rbac manifest to first master
  template:
    src: "vip.rbac.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/vip-rbac.yaml"
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Copy vip manifest to first master
  template:
    src: "vip.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/vip.yaml"
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Copy vip cc manifest to first master
  template:
    src: "vip.svc.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/vip-cc.yaml"
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Copy vip ippool config to first master
  template:
    src: "vip.ippool.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/vip-ippool.yaml"
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']
