---
- name: Disable and stop k3s
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  failed_when: false
  with_items:
    - k3s
    - k3s-control
    - k3s-node
    - k3s-init

- name: RUN pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  register: pkill_containerd_shim_runc
  ansible.builtin.command: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  changed_when: pkill_containerd_shim_runc.rc == 0
  failed_when: false

- name: Unmount kubelet mounts
  command: "find /var/lib/kubelet -type d -name 'kube-api-access-*' -exec umount {} \\;"
  ignore_errors: true

- name: Delete k3s related files
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/k3s
    - "/etc/systemd/system/k3s-control.service"
    - "/etc/systemd/system/k3s-node.service"
    - "/etc/systemd/system/k3s.service"
    - "/etc/systemd/system/k3s-init.service"
    - /etc/rancher/
    - /var/lib/kubelet
    - /var/lib/rancher/
    - /var/lib/cni/

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
